### ISSUE TITLE
Erro 403

### ISSUE THREAD

**Issue by integraCyber** [achambel/correios-tracker#10]
Não é possivel recuperar o status o rastreamento, sempre apresenta a mensagem de "Erro ao verificar status do objeto: 403"

**Comment by achambel** [comment]
Correios fecharam a API novamente. Solução seria usar a API que eles disponibilizam para quem tem contrato com eles. Eu não tenho contrato. Se vc tem ou conhece alguém que tem, podemos trabalhar numa implementação pra isso. Me contata em acmlima.softweb@gmail.com caso queira mais detalhes.
Grato.
