### ISSUE TITLE
[DUVIDA]

### ISSUE THREAD

**Issue by luizsaldanha** [achambel/correios-tracker#3]
É possível usar em uma web hospedagem?

**Comment by bolaum** [comment]
Como assim?

**Comment by luizsaldanha** [comment]
Se eu hospedar no meu site, vai rodar? digo, porque não costumo usar o mesmo computador :/

**Comment by luizsaldanha** [comment]
- Realizei o download do .zip
- Fiz o upload para a HOSTGATOR Servidor WEB
- Descompactei...
- Tentei acessar www.... não deu =/
como vi arquivos como .html , css, achei que poderia dar certo 
Se tiver como alterar algo pra fazer funcionar, me avisem 👍

**Comment by bolaum** [comment]
Esse repositório é para uma extensão do Chrome. Vc pode instalá-la em qq máquina que tiver o Chorme (https://chrome.google.com/webstore/detail/correios-tracker/nemepngjloclnhiflpcgkcbggnfbhjni).

Não foi feita para rodar a partir de um server.
