### ISSUE TITLE
Correios is using captcha now

### ISSUE THREAD

**Issue by douglashm** [achambel/correios-tracker#4]
I don't know if it is the right place, here. And also, it is not a bug, but Correios is now using captcha in the tracker tools.

**Comment by achambel** [comment]
Hi Douglas, thanks for letting me know. 
In addition to the captcha they also changed the response format. It comes in json now. A big effort will be need to change the extension.

**Comment by achambel** [comment]
Add new endpoint. We are not crawling the website anymore. We are using their endpoint instead.
https://github.com/achambel/correios-tracker/pull/5
