### ISSUE TITLE
Any perspective to fix the extension ?

### ISSUE THREAD

**Issue by joaopauloss** [achambel/correios-tracker#6]
Hi. 
First of all, thanks a lot for this awesome extension. In the period that it worked was really good, and for that I once made a donation for the project.
Is there any plan to fix it  (if it's possible, of course) ?

**Comment by achambel** [comment]
Hi Joao, I am working on a solution for adding a new endpoint to this extension. 
My plan is finish it by the end of the week. Let's see 🤞🏻
